name : play the game
on:
  issues:
    types: [opened]
jobs:
  playGame:
    runs-on: ubuntu-latest
    steps:
      - name: see the event id
        run: echo $EVENT_ID
        env:
          EVENT_ID: ${{ github.event.issue.id }}
